### ISSUE TITLE
bam file as input

### ISSUE THREAD

**Issue by matandro** [smithlabcode/piranha#8]
Hi,

I successfully build piranha with bamtools. When i attempt to run the software with my bam files I receive the following error:
`ERROR:	Responses cannot be provided in BAM format if they are not raw reads. Did you mean to use the -b or -z options?`

The input file is a sorted bam file generated by bowtie-2. The file was used in HTseq-count so I know it is not corrupted. So this is definitely not raw reads. Those are aligned reads.

Thanks,
Matan

**Comment by pjuren** [comment]
What the program calls "raw reads" is not the same as what you're thinking of. The default input format for Piranha is binned reads (i.e. counts of the number of reads occurring at each genomic locus you're interested in). When the error mentions "raw reads", it means what you are calling "aligned reads".

As the error message states, most likely you did not include the -z or -b option (which tells the program you are giving it reads, instead of counts). If you show me the command line you used to run it, I can offer more advice.

**Comment by matandro** [comment]
Hi,

Thanks for the replay. The run line I tried was:
`./Piranha  bowtie2_output_PullDown.bam bowtie2_output_TotalRNA.bam`
Both bam files are raw reads by your definition that are matched to a genome using bowtie 2 (matching both strands).
The data comes from a RIP-seq experiment where sequencing of pull down RNA is compared to total RNA.
I would like to identify peaks in the pull down data.

BTW, does the software handle biological repeats? or should I just merge the bam files of repeats?

Thanks,
Matan

**Comment by matandro** [comment]
Hey,

I played around with the software a bit and I still get weird issues:
1) I used the software with only the pull down bam file. I used the -b option (with 200 like in the paper, lso tried 51 which is my read length). The software suggest the my bam file isn't sorted (I know this to be false since I used it in other algorithms that require it to be sorted).

2) So when I add the -s option any way I get:
WARNING: Skipped 22893966 in BAM file /media/matan/BlastDB/Sample_4E_1_PD/L_mexicana/4E_1_PD_CTTGTA_L006_R1_clean_sorted.bam due to unknown reference IDs
Is this referencing reads that weren't matched to any location in the genome? does this mean 22m was skipped or read No. 22893966 was skipped?

3) When I tried running it with my total RNA genome as reference it told me again that it is not binned. It seems that the -b option is only relevant for the initial bam file and not all the input files.

Maybe if I transform my bam file it will work better. What is your transformation suggestion? What count tool did you use on your aligned reads?

**Comment by pjuren** [comment]
1. Piranha requires the file to be sorted by chromosome, start location, end location and then strand. Are you sure this Is the sort order your BAM file is sorted in?

2. Piranha tries to match each read to a chromosome ID in the index at the start of the BAM file; this error indicates that it didn't find a matching chromosome for a lot of the reads. Possibly your BAM file isn't in the format that is expected. In my experience, the BAM format is complicated and different tools tend to have slightly different interpretations of it. 

3. Yes, that's right. From the Readme (so you want either -z or -b and -i options):
> -b, -bin_size           indicates that input is raw reads and should be binned into bins of this size 
>  -i, -bin_size_covars    indicates that the covariates (all except first  file) are raw reads and should be > binned into bins of  this size 
>  -z, -bin_size_both      synonymous with -b x -i x for any x 

It'll probably be easier to convert your BAM files to BED. It's much easier to inspect that format on the command line to determine what might be wrong, and that is the native format used by Piranha. There are many tools for doing that; if you're having trouble finding one, I can recommend a few. I don't know any other programs for doing the read-counting, but I'm sure they're out there.

As for your earlier question, no, it doesn't handle either biological or technical replicates. You'll have to determine for yourself whether it makes sense to proceed with this kind of analysis if you have a complicated experimental design.

I'm going to close this issue because I think we're discussing how to use the program, rather than a bug. My contact email is in the readme -- we can continue by email if you're still having problems.
